### ISSUE TITLE
支持 getContainer 

### ISSUE THREAD

**Issue by eternalsky** [react-component/notification#11]
因为一些特殊的场景需要，需要能够像其他组件一样能够自定义 notification 的容器~

**Comment by afc163** [comment]
You can propose PR for it.

**Comment by eternalsky** [comment]
ok

**Comment by afc163** [comment]
https://github.com/react-component/notification/pull/12

You are in the same team?

**Comment by crapthings** [comment]
不认识，麻烦看一下，就是大概 pull 里边的意思
也许有更好的方案

**Comment by eternalsky** [comment]
不是一个 team 的，pr 的方案按照和 trigger 类似的设计，新增了 TC。

**Comment by afc163** [comment]
@crapthings 

@eternalsky 的实现和其他组件的风格更一致一些。

**Comment by crapthings** [comment]
我暂时把message全去掉了，期待新的功能

**Comment by benjycui** [comment]
@afc163 

```bash
➜  ~ npm owner ls rc-notification
afc163 <afc163@gmail.com>
yiminghe <yiminghe@gmail.com>
```

**Comment by afc163** [comment]
supported in 1.4.0
