### ISSUE TITLE
与 rc-util 4.0.2 版本不兼容

### ISSUE THREAD

**Issue by Darmody** [react-component/notification#18]
<img width="1053" alt="2017-06-27 12 59 21" src="https://user-images.githubusercontent.com/6788752/27571450-6ee5f552-5b38-11e7-8dac-24fef5842c9e.png">

**Comment by yesmeck** [comment]
需要 `^4.0.2`，PR 一个。

**Comment by yesmeck** [comment]
说错了，要 `^4.0.4`
