### ISSUE TITLE
How to use it with React 18 without warning

### ISSUE THREAD

**Issue by zpc7** [react-component/notification#192]
As you know, React 18 introduces a new root API which provides better ergonomics for managing roots.
> ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it’s running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

How to use current library without above warning?

In view of this, I want to submit a PR, but I don't know if I need to do a major version update for this situation (eg: limit `React` in `peerDependencies` to be greater than 18)? Or do not update the major version, just in the source code Can a React version be judged to be compatible?

---------

我尝试解决提PR, 采用了一个兼容修复这个警告的方法, 但是发现替换之后, 渲染执行的顺序跟以前不一样了.

背景: 源码中提供了2个示例(hooks和simple), 分别会先在开始去注册示例, 以hooks为例

`ReactDOM.render`时候, 渲染顺序如下: 
![image](https://user-images.githubusercontent.com/15316908/162685445-487953cf-8dd2-411c-8bbe-7b20418aa6d2.png)
可以看到, hooks示例中组件Demo在最后才开始渲染, 此时 `instance` 已经准备好了, 没有问题.

React 17 `createRoot...render()`时候, 渲染顺序如下: 
![image](https://user-images.githubusercontent.com/15316908/162686014-b6c7e492-821a-4279-88ad-77f8e9a7b2b0.png)
可以看到, 组件Demo并没有到最后才渲染, 渲染的时候 `instance` 还是`null`, 导致通过hooks的方式使用时, 会无法使用.

实在没找到好的解决方案和思路, 为了更好的表达, 我提交了一个 `Draft PR` https://github.com/react-component/notification/pull/193 , 期待大家参与讨论

---

更新: 通过对比发现, 可能是Dumi的问题, 参见: https://github.com/umijs/dumi/issues/1071

**Comment by abenhamdine** [comment]
fixed in https://github.com/react-component/notification/pull/203
