### ISSUE TITLE
Not working with react 18

### ISSUE THREAD

**Issue by sxwebdev** [react-component/notification#194]
Not working with react 18

<img width="433" alt="image" src="https://user-images.githubusercontent.com/3129246/162843990-445dba2f-d150-4e0e-9d80-ca4e96ad0a70.png">

**Comment by abenhamdine** [comment]
Can you try again with last version 4.6.0 ?
see also https://github.com/react-component/notification/pull/203

**Comment by sxwebdev** [comment]
I have upgraded the package `rc-notification` to version `4.6.0` and now I am getting the following error

<img width="435" alt="image" src="https://user-images.githubusercontent.com/3129246/163541629-974411ef-f88c-4cc5-ae94-680eee1e87b6.png">

**Comment by sxwebdev** [comment]
I deleted the `package-lock.json` file and deleted the `node_modules` folder. Then reinstalled the dependencies. After that all works as expected
