### ISSUE TITLE
removed 1.4.5 from npm repository

### ISSUE THREAD

**Issue by abonec** [react-component/notification#20]
We antd version 2.9.0 for a while in the development and when we will send it to pre stage our deployment was failed with error:
```
npm ERR! fetch failed https://registry.npmjs.org/rc-notification/-/rc-notification-1.4.5.tgz
npm ERR! fetch failed with status code 404
```

**Comment by paranoidjk** [comment]
It was unpublished due to some reason. Please just use the latest version, there is no breaking change.

**Comment by abonec** [comment]
@paranoidjk Is there no breaking changes in the whole antd library which I should upgrade?

**Comment by paranoidjk** [comment]
@abonec nope. Do you import `rc-notifiction` in your code ? Or you just use `antd` ?

**Comment by abonec** [comment]
I just use antd and notification from antd

**Comment by paranoidjk** [comment]
> I just use antd and notification from antd

Them you just need to reinstall you deps.

try `rm -rf node_modules && npm i ` or `yarn upgrade` if you use yarn

**Comment by abonec** [comment]
It still load 1.4.3 version.

**Comment by abonec** [comment]
All antd versions prior to 2.10.4 locked to ~1.4.0 rc notification.
Only latest locked to 2.0+
Can you return 1.4.3 version to repository?

**Comment by paranoidjk** [comment]
why you need 1.4.5？

**Comment by abonec** [comment]
Because somehow npm try to download 1.4.5 version and fail

**Comment by abonec** [comment]
![image](https://user-images.githubusercontent.com/240587/28174702-e3053fa0-67fa-11e7-9bfa-0490635c9492.png)

**Comment by paranoidjk** [comment]
Looks like you are using npm-shrinkwrap, you may need to to clean or upgrade the lockfile.
