### ISSUE TITLE
component does not work with React 16

### ISSUE THREAD

**Issue by abramobagnara** [react-component/notification#21]
The cause is the use of ReactDOM.render return value, that is an obsolete feature (also in React 15).
We should use ref instead.

https://facebook.github.io/react/docs/react-dom.html#render

**Comment by paranoidjk** [comment]
https://github.com/react-component/notification/blob/master/src/Notification.jsx#L99

**Comment by paranoidjk** [comment]
I think it should works fine, see the react document:

> Render a React element into the DOM in the supplied container and return a reference to the component (or returns null for stateless components).

**Comment by paranoidjk** [comment]
Please give a reproducible demo, and the detail error info.

**Comment by abramobagnara** [comment]
You can reproduce the crash using `npm install --save react@next react-dom@next`
and putting this reduced testcase in examples/test.js:

```
/* eslint-disable no-console */
import 'rc-notification/assets/index.less';
import Notification from 'rc-notification';
import React from 'react';
import ReactDOM from 'react-dom';
let notification;

function simpleFn() {
  notification.notice({
    content: <span>simple show</span>,
    onClose() {
      console.log('simple close');
    },
  });
}

class App extends React.Component {
  render() {
    return <div>hello</div>
  }
  componentDidMount() {
    notification = Notification.newInstance({});
    simpleFn();
  }
}

ReactDOM.render(<App/>, document.getElementById('__react-content'));
```

You will see in console:

`TypeError: Cannot read property 'add' of null`

**Comment by abramobagnara** [comment]
See https://github.com/facebook/react/issues/10309 for the clarification why this is a breaking changes in React 16 that will remain.

The point is that to use the return value of ReactDOM.render should be avoided in general.

**Comment by benjycui** [comment]
How about an online demo? 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by benjycui** [comment]
ping~ @paranoidjk

**Comment by paranoidjk** [comment]
@benjycui https://github.com/react-component/react-component.github.io/issues/14 

It's caused by rc-tools break change.

**Comment by paranoidjk** [comment]
@abramobagnara Please provide a reproducible demo, eg: https://codepen.io/paranoidjk/pen/NvxmKQ?editors=0011

@benjycui I found our umd dist do not handle `add-module-exports`, users must use  

`const Notification = window['rc-notification'].default;`

**Comment by abramobagnara** [comment]
This is a reproducible demo:

https://codepen.io/abramo/pen/ZJQgBL?editors=1111

**Comment by bkniffler** [comment]
Any news on this one?

**Comment by tvtri96** [comment]
I have the same error `TypeError: Cannot read property 'add' of null` as well. After upgrading to React 16, it doesn't work anymore.

**Comment by tylerlong** [comment]
I confirm that it doesn't work with React 16

**Comment by benjycui** [comment]
After upgrade to React@16...

If we use `Notification.newInstance` in lifecycle of a React component, we cannot get a ref from `ReactDOM.render` https://github.com/react-component/notification/blob/master/src/Notification.jsx#L99

But if we don't use `Notification.newInstance` in lifecycle, it works fine, just like http://react-component.github.io/notification/examples/simple.html

I think we must fix this issue, for developers may use `antd.notification` in lifecycle. And the simplest way may be make `Notification.newInstance` return a promise, instead of a ref directly.

cc @afc163 @paranoidjk

**Comment by paranoidjk** [comment]
https://github.com/facebook/react/issues/10294
> ReactDOM.render() and ReactDOM.unstable_renderIntoContainer() now return null if called from inside a lifecycle method.
To work around this, you can either use the new portal API or refs.

Looks like we need rewrite this with new portal api.

But i am pretty busy on another project these days. @silentcloud @benjycui @yesmeck @zhang740 Anybody want to handle this?

**Comment by yesmeck** [comment]
https://github.com/react-component/trigger/pull/69

**Comment by benjycui** [comment]
> Looks like we need rewrite this with new portal api.

Actually, we don't need to..

Even if we rewrite with `React.createPortal`, we still need to make `Notification.newInstance` async.

**Comment by benjycui** [comment]
See: https://github.com/react-component/notification/pull/27

We cannot use `React.createPortal`, for we don't want to change API in antd.
