### ISSUE TITLE
Apply new feature for notification component

### ISSUE THREAD

**Issue by HeZiGang** [react-component/notification#25]
Good day, 
I've some idea for the notification component and the user case as below. 

As a user I want to keep the notification layer on my screen when the mouse over it, because the information is too long, I cannot get all the information before the notification layer gone. if I can stop the timer then I can keep the notification dialog there for lang time. I think is would be very helpful.

Can add this function to next release and also add a config item to disable/enable this feature? thanks.

**Comment by benjycui** [comment]
Close in https://github.com/react-component/notification/pull/26
