### ISSUE TITLE
[v4.6.0] It seems that you should use `??` Instead of `| |`

### ISSUE THREAD

**Issue by kiner-tang** [react-component/notification#252]
- https://github.com/ant-design/ant-design/issues/38259

**Comment by kiner-tang** [comment]
I want to do it, but which branch should I develop on? It appears that the '5.x' version refactored this component. The problem is currently in version '4.x'！@zombieJ

**Comment by afc163** [comment]
master

**Comment by kiner-tang** [comment]
> master

The master branch should be '5.x' code, this version of the code does not have this problem, this problem should only appear in '4.x', should we upgrade the 'rc-notification' version to '5.0.0' in 'ant-design'? Or do we need a patch fix for version 4.x

**Comment by afc163** [comment]
> a patch fix for version 4.x

Just send PR to master branch.

**Comment by kiner-tang** [comment]
> > a patch fix for version 4.x
> 
> Just send PR to master branch.

But the code in the 'master' branch has been refactored, there is no '4.x' related problem code, in the branch list, only '3.x' and 'master' to choose from, which branch should I use as a benchmark for development?

**Comment by HelloBojack** [comment]
mater 代码已经是 5.0-alpha 版本了，没有这个问题了，这个问题出现在 4.6 之前版本，如果 antd 后面更新 rc-notification 到最新版，就没有问题了。所以这个bug，是不是 antd 等更新，不用修复了？

**Comment by kiner-tang** [comment]
> I checkout a new branch for 4.x to maintain: https://github.com/react-component/notification/tree/4.x

Great. I can fix it now

**Comment by afc163** [comment]
https://github.com/react-component/notification/tree/v4.6.1
