### ISSUE TITLE
Change the notification's background color.

### ISSUE THREAD

**Issue by rowthan** [react-component/notification#31]
I wonder to change the background color of notification.
```
notification.notice({
        content:
          <div className="bg-info">
            <span>添加成功！</span>
          </div>,
        closable: true,
        duration: 3.5,
      });
```
But have not change the nofitication, ugly, is not it?

Can you support some props to change the background of `.rc-notification-notice`

```
.rc-notification-notice {
  padding: 7px 20px 7px 10px;
  border-radius: 3px 3px;
  border: 1px solid #999;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
  border: 0px solid rgba(0, 0, 0, 0);
  background: #fff;
  display: block;
  width: auto;
  line-height: 1.5;
  vertical-align: middle;
  position: relative;
  margin: 10px 0;
}
```

**Comment by yutingzhao1991** [comment]
You can import your less to custom style.

`import 'rc-notification/assets/index.less';` -> `import './your.less';`

https://github.com/react-component/notification/blob/master/assets/index.less

**Comment by rowthan** [comment]
that's the point. 
sometimes, we do not care about styles. what we want to import is `rc-notification`.
so, i do think it is a good way to import `rc-notification`'s less file.
